# config.yml

backend:
  name: github
  repo: PixelAISite/www # replace this with your repo info
  branch: master # Branch to update (optional; defaults to master)
  use_graphql: true
  base_url: https://pixelai-cms-auth.trwerk.workers.dev/
media_folder: 'assets/images'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'select', options: [vulcan, cyberteam] }
      - { label: 'Topic', name: 'categories', widget: 'select', options: [Electronics, Space, Hardware, Code, AI, Wares, Reviews] }
      - { label: 'Flavours', name: 'tags', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image', choose_url: true, default: "assets/images/logo.png" }
      - { label: 'Image Alt', name: 'image_alt', widget: 'string' }
      - { label: 'Image Credit', name: 'image_credit', widget: 'string' }
      - { label: 'TOC', name: 'toc', widget: 'boolean', default: false }
      - { label: 'TOC Preface', name: 'beforetoc', widget: 'text', required: false }
      - { label: 'Rating', name: 'rating', widget: 'number', default: 0, value_type: "int", min: 0, max: 5, step: 1, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Summary', name: 'summary', widget: 'string' }

  - name: 'pages'
    label: 'Pages'
    folder: '_pages/'
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Permalink', name: 'permalink', widget: 'string'}
      - { label: 'Image', name: 'image', widget: 'image', choose_url: true, default: "assets/images/logo.png", required: false }
      - { label: 'Image Alt', name: 'image_alt', widget: 'string' }
      - { label: 'Image Credit', name: 'image_credit', widget: 'string' }
      - { label: 'Image Shadow', name: 'imageshadow', widget: 'boolean', default: false, required: false }
      - { label: 'Comments', name: 'comments', widget: 'boolean', default: false, required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Summary', name: 'summary', widget: 'string' }

